language: go

go:
 - 1.15

services:
  - xvfb

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y gcc libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

install: go get -d -v ./... && go build -v ./...

script: go test -v ./...
