// generated by stringer -type=Region; DO NOT EDIT

package nes

import "fmt"

const _Region_name = "NTSCPALUnknown"

var _Region_index = [...]uint8{0, 4, 7, 14}

func (i Region) String() string {
	if i+1 >= Region(len(_Region_index)) {
		return fmt.Sprintf("Region(%d)", i)
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
