// generated by stringer -type=RunState; DO NOT EDIT

package nes

import "fmt"

const _RunState_name = "UninitializedRunningQuitting"

var _RunState_index = [...]uint8{0, 13, 20, 28}

func (i RunState) String() string {
	if i+1 >= RunState(len(_RunState_index)) {
		return fmt.Sprintf("RunState(%d)", i)
	}
	return _RunState_name[_RunState_index[i]:_RunState_index[i+1]]
}
