// generated by stringer -type=RunState; DO NOT EDIT

package nes

import "fmt"

const _RunState_name = "RunningQuitting"

var _RunState_index = [...]uint8{7, 15}

func (i RunState) String() string {
	i -= 1
	if i >= RunState(len(_RunState_index)) {
		return fmt.Sprintf("RunState(%d)", i+1)
	}
	hi := _RunState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _RunState_index[i-1]
	}
	return _RunState_name[lo:hi]
}
