// generated by stringer -type=RunState; DO NOT EDIT

package nes

import "fmt"

const (
	_RunState_name_0 = "RunningPaused"
	_RunState_name_1 = "Quitting"
)

var (
	_RunState_index_0 = [...]uint8{7, 13}
	_RunState_index_1 = [...]uint8{8}
)

func (i RunState) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		lo := uint8(0)
		if i > 0 {
			lo = _RunState_index_0[i-1]
		}
		return _RunState_name_0[lo:_RunState_index_0[i]]
	case i == 4:
		return _RunState_name_1
	default:
		return fmt.Sprintf("RunState(%d)", i)
	}
}
