// generated by stringer -type=StepState; DO NOT EDIT

package nes

import "fmt"

const _StepState_name = "NoStepCycleStepScanlineStepFrameStep"

var _StepState_index = [...]uint8{0, 6, 15, 27, 36}

func (i StepState) String() string {
	if i+1 >= StepState(len(_StepState_index)) {
		return fmt.Sprintf("StepState(%d)", i)
	}
	return _StepState_name[_StepState_index[i]:_StepState_index[i+1]]
}
