// generated by stringer -type=StepState; DO NOT EDIT

package nes

import "fmt"

const (
	_StepState_name_0 = "NoStepCycleStep"
	_StepState_name_1 = "ScanlineStep"
	_StepState_name_2 = "FrameStep"
)

var (
	_StepState_index_0 = [...]uint8{6, 15}
	_StepState_index_1 = [...]uint8{12}
	_StepState_index_2 = [...]uint8{9}
)

func (i StepState) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		lo := uint8(0)
		if i > 0 {
			lo = _StepState_index_0[i-1]
		}
		return _StepState_name_0[lo:_StepState_index_0[i]]
	case i == 4:
		return _StepState_name_1
	case i == 8:
		return _StepState_name_2
	default:
		return fmt.Sprintf("StepState(%d)", i)
	}
}
