// generated by stringer -type=Mirroring; DO NOT EDIT

package rp2cgo2

import "fmt"

const _Mirroring_name = "HorizontalVerticalFourScreen"

var _Mirroring_index = [...]uint8{0, 10, 18, 28}

func (i Mirroring) String() string {
	if i+1 >= Mirroring(len(_Mirroring_index)) {
		return fmt.Sprintf("Mirroring(%d)", i)
	}
	return _Mirroring_name[_Mirroring_index[i]:_Mirroring_index[i+1]]
}
