// generated by stringer -type=Mirroring; DO NOT EDIT

package rp2cgo2

import "fmt"

const _Mirroring_name = "HorizontalVerticalFourScreen"

var _Mirroring_index = [...]uint8{10, 18, 28}

func (i Mirroring) String() string {
	if i >= Mirroring(len(_Mirroring_index)) {
		return fmt.Sprintf("Mirroring(%d)", i)
	}
	hi := _Mirroring_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Mirroring_index[i-1]
	}
	return _Mirroring_name[lo:hi]
}
